### ISSUE TITLE
Web Components communication

### ISSUE THREAD

**Issue by mbarqawi** [HedCET/TorrentAlert#86]
Hello, 
I would like to thank you for your work , it was very helpfull for me,
I have small question regarding how you are calling the inter components call between the elements 
you are using `document.querySelector("#torrent_db").value` for example but i think it should be cleaner to raise event and handle it from the container element 

I am correct? or I have misunderstanding 

BR

**Comment by HedCET** [comment]
@mbarqawi actually this is still under development, i am looking router(flowrouter) / event / mwc:mixin(MeteorJS package) based inter component communication

currently i just ported it from polymer-0.5

**Comment by HedCET** [comment]
@mbarqawi lets check now, mwc:compiler & mwc:mixin r implemented
