### ISSUE TITLE
high CPU usage 

### ISSUE THREAD

**Issue by iSuslov** [HedCET/TorrentAlert#87]
Hight CPU usage for me.. almost 100%. Is it because of polymer or background processes?

**Comment by HedCET** [comment]
@iSuslov i don't know, but here is the screenshot of my digital ocean 5$/month ubuntu instance

<img width="509" alt="untitled" src="https://cloud.githubusercontent.com/assets/1794209/13728596/df9e03a6-e943-11e5-8143-0c93618526b8.png">

which handling more than 50 simultaneous TorrentAlert Android App users

**Comment by HedCET** [comment]
@iSuslov it might be ur system dependent
